### ISSUE TITLE
enhance grafana with env vars and bind datasources and dashboards

### ISSUE THREAD

**Issue by hellt** [srl-labs/srl-telemetry-lab#1]
```yaml
grafana:
   container_name: grafana
   environment:
     GF_SECURITY_ADMIN_USER: admin
     GF_SECURITY_ADMIN_PASSWORD: admin
     GF_INSTALL_PLUGINS: natel-discrete-panel
     GF_PATHS_PROVISIONING: /etc/grafana/provisioning
   ports:
     - '3000:3000'
   image: grafana/grafana:7.0.3
   volumes:
      - $PWD/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - $PWD/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - $PWD/dashboards:/var/tmp/dashboards
```
